global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'prod-monitor'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

rule_files:
  - '/etc/prometheus/rules.yml'
  - '/etc/prometheus/alerts.yml'


scrape_configs:
#-----------promethus-----------------------------
- job_name: 'prometheus'
  static_configs:
  - targets: ['192.168.43.10:9090']


# BEGIN ANSIBLE MANAGED BLOCK
#--------------timesheet-devops-service---------------------------------
- job_name: 'timesheet-devops-service'
  metrics_path: '/timesheet-devops/actuator/prometheus'
  static_configs:
  - targets:
    - '192.168.43.10:8079'
    labels:
      group: 'timesheet-API'
# END ANSIBLE MANAGED BLOCK


# BEGIN vm_monitor  BLOCK
#--------------vm-host---------------------------------
- job_name: 'local_vm_node_exporter'
  metrics_path: '/metrics'
  static_configs:
  - targets:
    - '192.168.43.10:9100'
    labels:
      group: 'local_vm_host'
# END ANSIBLE MANAGED BLOCK


# BEGIN vm_monitor  BLOCK
#--------------Jenkins---------------------------------
- job_name: 'jenkins'
  metrics_path: '/prometheus'
  static_configs:
  - targets:
    - '192.168.43.10:8080'
    labels:
      group: 'jenkins_server'
# END ANSIBLE MANAGED BLOCK

